services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: dspcoder
      POSTGRES_PASSWORD: dspcoder
      POSTGRES_DB: dspcoder
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
