version: "3.8"

services:
  # Django service (if needed)
  dspserver:
    build: server/DSPserver
    ports:
      - "8000:8000"
    volumes:
      - ./server/DSPserver:/app

  # Next.js service (if needed)
  nextjs:
    build: apps/next
    ports:
      - "3000:3000"
    volumes:
      - ./apps/next:/app
