FROM node:20-alpine 
WORKDIR /app
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable
COPY package.json .  
COPY pnpm-lock.yaml  .
RUN pnpm install --frozen-lockfile  
EXPOSE 3000
CMD [ "npm", "run", "dev" ]  