const ProblemsData = [
  {
    id: 1105,
    title: "Filling Bookcase Shelves",
    acceptanceRate: "68.6%",
    difficulty: "Medium",
    totalSubmissions: 12000,
    acceptedSubmissions: 8200,
    solution: true,
  },
  {
    id: 1,
    title: "Two Sum",
    acceptanceRate: "53.3%",
    difficulty: "Easy",
    totalSubmissions: 200000,
    acceptedSubmissions: 106600,
    solution: true,
  },
  {
    id: 2,
    title: "Add Two Numbers",
    acceptanceRate: "43.6%",
    difficulty: "Medium",
    totalSubmissions: 150000,
    acceptedSubmissions: 65400,
    solution: true,
  },
  {
    id: 3,
    title: "Longest Substring Without Repeating Characters",
    acceptanceRate: "35.2%",
    difficulty: "Medium",
    totalSubmissions: 180000,
    acceptedSubmissions: 63360,
    solution: true,
  },
  {
    id: 4,
    title: "Median of Two Sorted Arrays",
    acceptanceRate: "40.9%",
    difficulty: "Hard",
    totalSubmissions: 130000,
    acceptedSubmissions: 53170,
    solution: true,
  },
  {
    id: 5,
    title: "Longest Palindromic Substring",
    acceptanceRate: "34.2%",
    difficulty: "Medium",
    totalSubmissions: 160000,
    acceptedSubmissions: 54720,
    solution: true,
  },
  {
    id: 6,
    title: "Zigzag Conversion",
    acceptanceRate: "48.8%",
    difficulty: "Medium",
    totalSubmissions: 140000,
    acceptedSubmissions: 68320,
    solution: true,
  },
  {
    id: 7,
    title: "Reverse Integer",
    acceptanceRate: "28.9%",
    difficulty: "Medium",
    totalSubmissions: 210000,
    acceptedSubmissions: 60690,
    solution: true,
  },
  {
    id: 8,
    title: "String to Integer (atoi)",
    acceptanceRate: "17.7%",
    difficulty: "Medium",
    totalSubmissions: 230000,
    acceptedSubmissions: 40710,
    solution: false,
  },
  {
    id: 9,
    title: "Palindrome Number",
    acceptanceRate: "57.1%",
    difficulty: "Easy",
    totalSubmissions: 220000,
    acceptedSubmissions: 125620,
    solution: true,
  },
  {
    id: 10,
    title: "Regular Expression Matching",
    acceptanceRate: "28.3%",
    difficulty: "Hard",
    totalSubmissions: 240000,
    acceptedSubmissions: 67920,
    solution: false,
  },
  {
    id: 11,
    title: "Container With Most Water",
    acceptanceRate: "55.8%",
    difficulty: "Medium",
    totalSubmissions: 110000,
    acceptedSubmissions: 61380,
    solution: true,
  },
  {
    id: 12,
    title: "Integer to Roman",
    acceptanceRate: "65.7%",
    difficulty: "Medium",
    totalSubmissions: 100000,
    acceptedSubmissions: 65700,
    solution: true,
  },
];

export default ProblemsData;
