name: Build and deploy Node.js app to Azure Web App - dspcoder-FE

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Install pnpm globally
        run: |
          npm install -g pnpm

      - name: Verify pnpm installation
        run: pnpm --version

      - name: Install dependencies with pnpm
        run: pnpm install

      - name: Build the app with TurboRepo
        run: pnpm turbo run build --filter=next...

      - name: Zip artifact for deployment
        run: zip -r release.zip ./dist

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read # This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_BB0CB07D734A4059A858F8920B07E950 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_540F4D21549A41469EEC6E06A4DBF737 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_0A43E3F68A504A8989134E2E8AB98559 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: "dspcoder-FE"
          slot-name: "Production"
          package: .
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PROD_DB: ${{ secrets.PROD_DB }}
          DATABASE_NAME: ${{ secrets.DATABASE_NAME }}
          PORT: ${{ secrets.PORT }}
          SERVER: ${{ secrets.SERVER }}
          AZURE_LOCATION: ${{ secrets.AZURE_LOCATION }}
          AZURE_IMAGE_NAME: ${{ secrets.AZURE_IMAGE_NAME }}
          AZURE_CLIENT_PASSWORD: ${{ secrets.AZURE_CLIENT_PASSWORD }}
          AZURE_PRINCIPAL_NAME: ${{ secrets.AZURE_PRINCIPAL_NAME }}
          AZURE_REGISTRY_USERNAME: ${{ secrets.AZURE_REGISTRY_USERNAME }}
          AZURE_REGISTRY_PASSWORD: ${{ secrets.AZURE_REGISTRY_PASSWORD }}
          AZURE_RENODE_REGISTRY: ${{ secrets.AZURE_RENODE_REGISTRY }}
          AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
          AZURE_SUBSCRIPTION_NAME: ${{ secrets.AZURE_SUBSCRIPTION_NAME }}
          AZURE_PORT: ${{ secrets.AZURE_PORT }}
          PROBLEMS_COLLECTION: ${{ secrets.PROBLEMS_COLLECTION }}
          BLOGS_COLLECTION: ${{ secrets.BLOGS_COLLECTION }}
          AZURE_BLOB_CONNECTION_STRING: ${{ secrets.AZURE_BLOB_CONNECTION_STRING }}
